
name: Quality Gate Workflow

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually
    inputs:
      commit_id:
        description: "Commit ID to send to CICD Manager"
        required: true
        default: "a69563594f226af4aa768b281fb393564704ab88"   

jobs:
  QualityGate-GitActionWorkflow:
    runs-on: windows-latest

    steps:
      - name: Display a message
        run: echo "This workflow was triggered from GuideWire quality Gates!"

      - name: Show commitId input
        run: echo "CommitId input was ${{ github.event.inputs.commit_id }}"

      - name: Run GW Tests
        run: sleep 5

      - name: Security and Vulnerbality Check
        run: sleep 5

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Gosu Distribution
        shell: bash
        run: |
          echo "Downloading Gosu distribution..."
          curl -L -o gosu.zip http://search.maven.org/remotecontent?filepath=org/gosu-lang/gosu/gosu/1.14.16/gosu-1.14.16-full.zip
          unzip gosu.zip -d gosu_dist
  
      - name: Find gosu.cmd
        id: find_gosu
        shell: pwsh
        run: |
            $gosu = Get-ChildItem -Path gosu_dist -Recurse -Filter "gosu.cmd" | Select-Object -First 1
            if (-not $gosu) {
              Write-Error "gosu.cmd not found!"
              exit 1
            }
            echo "Found gosu.cmd at $($gosu.FullName)"
            echo "GOSU_CMD=$($gosu.FullName)" | Out-File -FilePath $Env:GITHUB_ENV -Append
  
      - name: Clean previous builds
        shell: cmd
        run: |
          echo Cleaning old build artifacts...
          if exist dist rmdir /s /q dist
      
      - name: Validate Gosu Files
        shell: cmd
        run: |
          echo Validating all Gosu files...
          for /R src %%f in (*.gs) do (
            echo Checking syntax of %%f
            call "%GOSU_CMD%" -c %%f || exit /b 1
          )
      
      - name: Build Gosu Applications
        shell: cmd
        run: |
          echo Building Gosu applications...
          if exist dist rmdir /s /q dist
          if exist build-app.bat (
            call build-app.bat
          ) else (
            echo "⚠ build-app.bat not found, skipping build."
          )

      - name: PII Scan for .gs files
        shell: cmd
        run: |
          @echo off
          echo PII Scan Report - %date% %time%
          echo =================================================
          echo.
      
          rem Initialize variable to track PII detection
          set "PII_FOUND=0"
      
          rem Scan all .gs files in the root folder
          for %%f in ("%GITHUB_WORKSPACE%\*.gs") do (
              echo Scanning file: %%f
      
              findstr /R /C:"[a-zA-Z0-9._%+-]*@[a-zA-Z0-9.-]*\.[a-zA-Z][a-zA-Z]*" "%%f" >nul && (
                  echo   Email: Found
                  set "PII_FOUND=1"
              ) || echo   Email: None
      
              findstr /R /C:"[0-9][0-9][0-9][-.]?[0-9][0-9][0-9][-.]?[0-9][0-9][0-9][0-9]" "%%f" >nul && (
                  echo   Phone: Found
                  set "PII_FOUND=1"
              ) || echo   Phone: None
      
              findstr /R /C:"[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]" "%%f" >nul && (
                  echo   SSN: Found
                  set "PII_FOUND=1"
              ) || echo   SSN: None
      
              findstr /R /C:"[0-9][0-9][0-9][0-9][ -]?[0-9][0-9][0-9][0-9][ -]?[0-9][0-9][0-9][0-9][ -]?[0-9][0-9][0-9][0-9]" "%%f" >nul && (
                  echo   Credit Card: Found
                  set "PII_FOUND=1"
              ) || echo   Credit Card: None
      
              echo.
          )
      
          rem Exit with code 1 if any PII was found
          if %PII_FOUND%==1 (
              echo ⚠ PII detected! Failing the workflow step...
              exit /b 1
          ) else (
              echo ✅ No PII detected. Task completed successfully.
              exit /b 0
          )


      
    
      - name: Run a script
        run: |
          echo "All Test Cases passed successfully."     
     
      - name: Call CICD Manager Quality Gate API
        shell: pwsh
        run: |
          $commitId = "${{ github.event.inputs.commit_id }}"
          $headers = @{
            "Authorization" = "Bearer ${{ secrets.CICD_TOKEN }}"
            "Content-Type"  = "application/json"
          }

          $body = @{
            artifact = @{
              type = "COMMIT"
              id   = $commitId
            }
            status  = "SUCCESSFUL"
            url     = "https://bitbucket.example.com/browse/GWCP-0000"
            comment = "Verification Passed from GitHub Actions"
          } | ConvertTo-Json -Depth 3

          $response = Invoke-RestMethod -Uri "https://cicd-manager-service.api.omega2-andromeda.guidewire.net/api/v3/tenants/valuemom/starsystems/gwcp/applications/cm/quality-gates/usaaqualitygatedemo/verifications" `
                                        -Method POST `
                                        -Headers $headers `
                                        -Body $body `
                                        -ErrorAction Stop

          Write-Host "✅ CICD Manager API call successful"
          Write-Host $response | ConvertTo-Json -Depth 5

