name: PII Data Scan Pipeline

on:
  push:
    branches: [ none ]
  pull_request:
    branches: [ none ]
  workflow_dispatch:
  
jobs:
  pii-scan:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Gosu Runtime
      run: |
        echo "Setting up Gosu runtime..."
        set GOSU_CLASSPATH=gosu\gosu.jar
        set PATH=%PATH%;%CD%
        
    - name: Build Gosu Applications
      run: |
        echo "Building Gosu applications..."
        call build-app.bat
        
    - name: Run PII Data Scan
      run: |
        echo "Scanning for PII data..."
        java -cp "gosu\gosu.jar" gw.lang.Gosu PIIScanner.gs
        
    - name: Upload PII Scan Report
      uses: actions/upload-artifact@v3
      with:
        name: pii-scan-report
        path: pii-scan-report.log
        
    - name: Display Report Summary
      run: |
        echo "PII Scan Report Summary:"
        type pii-scan-report.log
