name: PII Data Scan Pipeline

on:
  workflow_dispatch:
  
jobs:
  pii-scan:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Download Gosu Distribution
      shell: bash
      run: |
        echo "Downloading Gosu distribution..."
        curl -L -o gosu.zip https://github.com/gosu-lang/gosu-lang/releases/download/v1.14.18/gosu-1.14.18.zip
        unzip gosu.zip -d gosu_dist

    - name: Verify Gosu Unzip
      shell: cmd
      run: |
        echo Listing Gosu dist folder...
        dir gosu_dist
        echo Listing Gosu bin folder...
        dir gosu_dist\gosu-1.14.18\bin

    - name: Build Gosu Applications
      shell: cmd
      run: |
        echo Building Gosu applications...
        if exist dist rmdir /s /q dist
        build-app.bat

    - name: Run PII Data Scan
      shell: cmd
      run: |
        echo Running PII Scanner...
        gosu_dist\gosu-1.14.18\bin\gosu.cmd PIIScanner.gs
        
    - name: Upload PII Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: pii-scan-report
        path: pii-scan-report.log
        
    - name: Display Report Summary
      shell: cmd
      run: |
        echo PII Scan Report Summary:
        type pii-scan-report.log
