name: PII Data Scan Pipeline

on:
  push:
    branches: [ none ]
  pull_request:
    branches: [ none ]
  workflow_dispatch:
  
jobs:
  pii-scan:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Download Gosu Runtime
      shell: bash
      run: |
        echo "Downloading Gosu runtime..."
        mkdir -p gosu/lib
        curl -L -o gosu/lib/gosu-core.jar https://repo1.maven.org/maven2/org/gosu-lang/gosu-core/1.14.18/gosu-core-1.14.18.jar
        curl -L -o gosu/lib/gosu-lang.jar https://repo1.maven.org/maven2/org/gosu-lang/gosu/1.14.18/gosu-1.14.18.jar
        curl -L -o gosu/lib/gosu-parser.jar https://repo1.maven.org/maven2/org/gosu-lang/gosu-parser/1.14.18/gosu-parser-1.14.18.jar

    - name: Verify Gosu JARs
      shell: cmd
      run: |
        echo Listing Gosu lib directory...
        dir gosu\lib

    - name: Build Gosu Applications
      shell: cmd
      run: |
        echo Building Gosu applications...
        if exist dist rmdir /s /q dist
        build-app.bat

    - name: Run PII Data Scan
      shell: cmd
      run: |
        echo Running PII Scanner with Java + Gosu runtime...
        gosu_dist\gosu-1.14.18\bin\gosu.cmd PIIScanner.gs
        
    - name: Upload PII Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: pii-scan-report
        path: pii-scan-report.log
        
    - name: Display Report Summary
      shell: cmd
      run: |
        echo PII Scan Report Summary:
        type pii-scan-report.log
